{
 "title": "Net Traffic Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "query_result(count_over_time(v2ray_traffic_downlink_bytes_total[$__range]))"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "query_result(count_over_time(v2ray_traffic_downlink_bytes_total{job=\"$job\"}[$__range]))"
   },
   {
    "name": "target",
    "label": "Target",
    "query": "query_result(count_over_time(v2ray_traffic_downlink_bytes_total{job=\"$job\"}[$__range]))"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Online",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(v2ray_up{job=~\"$job\",instance=~\"$instance\"} == 1)"
    }
   ]
  },
  {
   "title": "Real-Time Overview",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 10, "x": 2, "y": 1 },
   "targets": [
    {
     "expr": "v2ray_uptime_seconds{job=~\"$job\",instance=~\"$instance\"}"
    },
    {
     "expr": "sum by (instance) (increase(v2ray_traffic_downlink_bytes_total{job=~\"$job\",instance=~\"$instance\"}[$__range]))"
    },
    {
     "expr": "sum by (instance) (increase(v2ray_traffic_uplink_bytes_total{job=~\"$job\",instance=~\"$instance\"}[$__range]))"
    }
   ]
  },
  {
   "title": "$target Bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(v2ray_traffic_downlink_bytes_total{job=~\"$job\",target=~\"$target\"}[5m]))",
     "legendFormat": "Downlink"
    },
    {
     "expr": "sum(irate(v2ray_traffic_uplink_bytes_total{job=~\"$job\",target=~\"$target\"}[5m]))",
     "legendFormat": "Uplink"
    }
   ]
  },
  {
   "title": "Node Offline",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(v2ray_up{job=~\"$job\",instance=~\"$instance\"}) - count(v2ray_up{job=~\"$job\",instance=~\"$instance\"} == 1)"
    }
   ]
  },
  { "title": "$instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }, "repeat": "instance" },
  {
   "title": "Api status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(v2ray_traffic_downlink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=\"inbound\",target=\"api\"}[20s])",
     "legendFormat": "{{target}}"
    },
    {
     "expr": "irate(v2ray_traffic_uplink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=\"inbound\",target=\"api\"}[20s])"
    }
   ]
  },
  {
   "title": "Real-Time Detail Overview",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 8 },
   "targets": [
    {
     "expr": "increase(v2ray_traffic_downlink_bytes_total{job=~\"$job\",instance=~\"$instance\"}[$__range])"
    },
    {
     "expr": "increase(v2ray_traffic_uplink_bytes_total{job=~\"$job\",instance=~\"$instance\"}[$__range])"
    }
   ]
  },
  {
   "title": "All Bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(v2ray_traffic_downlink_bytes_total{job=~\"$job\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "Downlink"
    },
    {
     "expr": "sum(irate(v2ray_traffic_uplink_bytes_total{job=~\"$job\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "Uplink"
    }
   ]
  },
  {
   "title": "$instance inbound download status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(v2ray_traffic_downlink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=~\"inbound\"}[5m])",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "$instance inbound upload status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(v2ray_traffic_uplink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=~\"inbound\"}[5m])",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "$instance user download status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(v2ray_traffic_downlink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=~\"user\"}[5m])",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "$instance user upload status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(v2ray_traffic_uplink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=~\"user\"}[5m])",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "$instance iptables download status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(v2ray_traffic_downlink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=~\"iptables\"}[5m])",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "$instance iptables upload status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(v2ray_traffic_uplink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=~\"iptables\"}[5m])",
     "legendFormat": "{{target}}"
    }
   ]
  },
  { "title": "$instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Api status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(v2ray_traffic_downlink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=\"inbound\",target=\"api\"}[20s])",
     "legendFormat": "{{target}}"
    },
    {
     "expr": "irate(v2ray_traffic_uplink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=\"inbound\",target=\"api\"}[20s])"
    }
   ]
  },
  {
   "title": "Real-Time Detail Overview",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 36 },
   "targets": [
    {
     "expr": "increase(v2ray_traffic_downlink_bytes_total{job=~\"$job\",instance=~\"$instance\"}[$__range])"
    },
    {
     "expr": "increase(v2ray_traffic_uplink_bytes_total{job=~\"$job\",instance=~\"$instance\"}[$__range])"
    }
   ]
  },
  {
   "title": "All Bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(v2ray_traffic_downlink_bytes_total{job=~\"$job\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "Downlink"
    },
    {
     "expr": "sum(irate(v2ray_traffic_uplink_bytes_total{job=~\"$job\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "Uplink"
    }
   ]
  },
  {
   "title": "$instance inbound download status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(v2ray_traffic_downlink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=~\"inbound\"}[5m])",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "$instance inbound upload status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(v2ray_traffic_uplink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=~\"inbound\"}[5m])",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "$instance user download status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(v2ray_traffic_downlink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=~\"user\"}[5m])",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "$instance user upload status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(v2ray_traffic_uplink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=~\"user\"}[5m])",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "$instance iptables download status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(v2ray_traffic_downlink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=~\"iptables\"}[5m])",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "$instance iptables upload status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(v2ray_traffic_uplink_bytes_total{job=~\"$job\",instance=~\"$instance\",dimension=~\"iptables\"}[5m])",
     "legendFormat": "{{target}}"
    }
   ]
  }
 ]
}